export enum MENU_ITEM_LABELS_E {
	HOME = 'HOME',
	FAVORITES = 'FAVORITES',
	CART = 'CART',
	NOTIFICATIONS = 'NOTIFICATIONS',
	PROFILE = 'PROFILE',
	PRODUCT_DETAIL = 'PRODUCT_DETAIL',
}

export const INITIAL_ROUTE_NAME = MENU_ITEM_LABELS_E.HOME;
